### PR TITLE
Support for shorthand _(), _p(), _n(), _pn(), expanded c# extensions and --order sorting method

### PR DESCRIPTION
**Pull request by hakakou**
Made a small change to ```GetText.Extractor``` to find strings using a shorthand syntax, like:

```cs
_("Hello, World!"); // GetString
_n("You have {0} apple.", "You have {0} apples.", count, count); // GetPluralString
_p("Context", "Hello, World!"); // GetParticularString
_pn("Context", "You have {0} apple.", "You have {0} apples.", count, count); // GetParticularPluralString
```
A simple static class with such extensions is here: https://github.com/VitaliiTsilnyk/NGettext/blob/master/samples/NGettextShortSyntax.cs

### CODE REVIEW

**Comment by hakakou** [comment]
Also added support for *.razor and *.cshtml, and a changed the sorting method when --order is used. 

With --order, the items are sorted based on filename and then line number. This makes it easier to translate in poedit for example, as the message ids follow the logical order as found in the source code filenames and then line numbers.

**Review by perpetualKid — CHANGES_REQUESTED** [review]
Thank you for your contributions, appreciated! 
Having all of the changes in a single PR makes it more difficult to comment and align with the goals, but I'll try to address each individually.

**Review by perpetualKid — APPROVED** [review]
Great finding, which was asked for before here #35. 
Preliminary research (probably based on older versions of the engine) didn't showed success, but testing proves this obviously now works with razor files as well.

**Review by perpetualKid — CHANGES_REQUESTED** [review]
For texts which occur multiple times, this only works consistently when the occurrences are all contained with the same file. 
For the (not so uncommon) case of references across multiple files, the order of references is pretty much unpredictable due to parallelism, which again would make the sorted output variable each time.  
Going with your approach, you would also need to sort the references, which still leaves the case when texts (and thus resulting references) are removed in a files, the sort order would change again.
Translators may not follow source code at all, so for them this is less relevant. (Stable) sort order was introduced to make po templates comparable, limiting to real diffs only instead of "artificial" diffs caused by reordering only.

If you see a need for the sort order you implemented, we should make this overall configurable   in a different way, i.e. having an argument to the --order option to specify which way to order the output.

**Comment by hakakou** [comment]
Sorry for sloppy bundling in a single PR. I agree with the --order param. Should I remove the commit (that has to do the ordering) and leave the other two? I'll do separate work on the ordering in another PR.

**Review by perpetualKid — CHANGES_REQUESTED** [review]
I'm hesitant to incorporate this change to the core source. 
While I understand the heritage of the shortcuts, they are not part of GetText.Net (nor even NGetText) but only available as custom aliases externally. 
The notion does not align with common .NET/C# style guides and naming convention, in particular the simple underscore term ("_") could easily confused by developers who are not familiar with gettext history with other common language terms (discard symbol).

I'd be open to implement customizable extensions to allow for additional/arbitrary aliases in a generic way.

**Comment by perpetualKid** [comment]
> I agree with the --order param. 
... I'll do separate work on the ordering in another PR.

let's do that in a separate PR, yes. LMK if you want help with the [commandline](https://github.com/dotnet/command-line-api) stuff which may be bit hassle to begin with

**Comment by hakakou** [comment]
> I'm hesitant to incorporate this change to the core source. While I understand the heritage of the shortcuts, 

OK. Could I support them then separately, by introducing a command line option, for example "--extended" ? This way these c# extension (like _, _p etc) would be scanned only if the command line argument is added.

**Comment by perpetualKid** [comment]
> OK. Could I support them then separately, by introducing a command line option, for example "--extended" ? This way these c# extension (like _, _p etc) would be scanned only if the command line argument is added.

this wouldn't solve the underlying issue/need to hardcode such shortcuts (or any other aliases) into the extractor source, but only tries to hide them. Which doesn't even make sense once they would have been implemented.

There has been another discussion to ie allow for other control properties to be extracted, but I can only see two options to make customizations generically work:
- the list of methods/properties/attributes in ParserBase are somehow made configurable for external configuration (which in your case would still require also to change the parse logic like you did and scan for IdentifierNameSyntax also as you are no longer parse for member methods). 
- implement a custom version for your purposes.

Happy to help or join forces and work on an implementation for the first approach.

For reference, I also removed the shortcut syntax example (09740a3bcdcb539801492333b162c928efbc5e03) which was inherited from NGetText to make clear this is not part of the solution.

**Comment by Owlblocks** [comment]
Is this still a possibility (configurable aliases)? And if @hakakou doesn't want to do it, would it be very difficult? It doesn't seem so, so I could try my hand at it.

**Comment by perpetualKid** [comment]
> Is this still a possibility (configurable aliases)? And if @hakakou doesn't want to do it, would it be very difficult? It doesn't seem so, so I could try my hand at it.

requires either a bunch of parameters to be passed for the aliases, or a config file which could resolve any number of options. The former could be implemented by extending the existing code with new arguments, however the command line will become pretty extensive. The latter would be a whole new approach, so some plumbing will be needed.

**Comment by perpetualKid** [comment]
I'm closing this PR as the underlying ideas are included now

**Pull request closed without merging**
